### ISSUE TITLE
Make th default behaviour of `duty` (without args) more user-friendly

### ISSUE THREAD

**Issue by sfermigier** [pawamoy/duty#11]
I find the current behaviour of `duty` called without arguments a bit dry:

```
duty
> Please choose at least one duty
```

It could either:

1) List the available duties (in addition to the dry message above). This is probably quite easy to implement.

2) Or provide a way to select a duty from a list using the arrow keys, like the Fish shell (and probably others) do. This is probably a bit harder and may need a third-party dependency.

**Comment by pawamoy** [comment]
Thanks for the suggestion, I've done that in v0.11.1. Running `duty` with no args will now show the help and available duties and exit with code 1 :slightly_smiling_face:
