### ISSUE TITLE
Add some use-cases or comparisons to `invoke` and/or `Make`

### ISSUE THREAD

**Issue by Kilo59** [pawamoy/duty#5]
In most of my projects I typically either use `invoke` or `Make` a comparison to these tools in the project readme would help users quickly evaluate `duty` and whether or not to use it.

**Comment by pawamoy** [comment]
Hello, thank you very much for the suggestion! This is a good idea, I'll try to come up with something.

**Comment by ItsAleph** [comment]
[Taskfile](https://taskfile.dev/) is used quite widely too. I believe mkdocs code tabs will perfectly fit this need

**Comment by sfermigier** [comment]
Indeed, it would be very interesting to document how duty improves upon invoke, and differs.

FYI: I just translated an existing `tasks.py` to a `duties.py`, by replacing all the `@task`s by `@duty`s. It worked, until it didn't (one of my tasks calls an interactive script over ssh, and duty seemed to hang on it while invoke didn't).

**Comment by pawamoy** [comment]
Sorry for the trouble :/ Could you open a 'ew issue describing the problem? I'd be happy to bring support for interactive scripts.

**Comment by pawamoy** [comment]
I've added a small section to the docs. Improvements and suggestions are welcome.
https://pawamoy.github.io/duty/#why-duty-over
