### ISSUE TITLE
Duty doesn't deal with interactive commands (like Invoke does)

### ISSUE THREAD

**Issue by sfermigier** [pawamoy/duty#9]
After converting an invoke script to duty, I found that commands that asked for interaction didn't work as well (or at all).

Here's the simplest example that I could make:

```
@duty
def debug(c):
    c.run(f'touch /tmp/toto.txt')
    c.run(f'rm -i /tmp/toto.txt')
```

In this case, it still works but the prompt doesn't appear. In my original case, which calls certbot over ssh, which in itself asks for a prompt, it doesn't work at all. 

Both cases work with Invoke.

**Comment by sfermigier** [comment]
OK, it works in both cases with `capture=False`.

Thanks for the help.

IMHO this illustrates the need to write down the differences (both in goals/scope and API details) with Invoke.

I'd also argue that Invoke works "out of the box" for this particular use case, though I don't know if there are important uses cases were `capture=True` bu default makes more sense.

**Comment by pawamoy** [comment]
Yep, working on some docs right now.

One of duty's goal is minimalist output, so capturing output is wanted in almost all cases. The exception is... interactive commands, which are, in my experience, rare enough in a task runner context :slightly_smiling_face:
